### ISSUE TITLE
Allow to choose default style

### ISSUE THREAD

**Issue by dsgh** [el/style-switcher#10]
Currently, there's no way to change the default style of 'Streets'. Even if the map starts with a different style, the selector will not show the map's initial style as active, it will show Streets as active.

It would be great if either we could pass in the default style (maybe as second parameter to `MapboxStyleSwitcherControl`?), or if it would "read" from the map what style is there as default, and start with that.

Thoughts?

**Comment by el** [comment]
Hey, happy to accept a PR for this.
