### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by cristianodri** [el/style-switcher#13]
Hello, 

ho do I intercept mouse click event on style-switcher control?

**Comment by el** [comment]
No way to do that right now, what is your use case? Maybe I can add that functionality

**Comment by cristianodri** [comment]
when style changes, mapbox removes custom layers on map and so I need to intercept the mouse click to know when the user changes style and be able to reload the custom layers

**Comment by el** [comment]
I have added events, the version has been published as 1.0.10

**Comment by cristianodri** [comment]
Oh great! Thank you very much
