### ISSUE TITLE
Add MapLibre support

### ISSUE THREAD

**Issue by jimmyangel** [el/style-switcher#14]
Have you considered supporting [MapLibre](https://github.com/maplibre/maplibre-gl-js)?

**Comment by el** [comment]
I have not, what is broken in MapLibre?

**Comment by jimmyangel** [comment]
Never mind, it works like a charm!

**Comment by jimmyangel** [comment]
Well, since version 1.15 of maplibre, this library stopped working. The issue is that maplibre has renamed all the css classes from ```mapboxgl-``` to ```maplibregl-```. For example ```mapboxgl-ctrl``` is now ```maplibregl-ctrl```. So the library does not find the classes.

**Comment by el** [comment]
@jimmyangel that is a simple css issue that can easily be workaround. I am closing the issue since it is a niche problem. If anyone wants to add support, PRs are open.
