### ISSUE TITLE
Use without NPM?

### ISSUE THREAD

**Issue by eiiot** [el/style-switcher#15]
I've noticed that many plugins allow users to use an api.mapbox.com URL to import the plugin into an HTML file. Is this possible with style-switcher? If so, what is the URL?

**Comment by MammaClaudia** [comment]
Hi! I've install the style-switcher with yarn.

`yarn add i mapbox-gl-style-switcher --save`

**Comment by el** [comment]
@EliotHertenstein Can you give me an example? I think you are talking about the official plugins created by Mapbox. 

You can try `https://unpkg.com/mapbox-gl-style-switcher`
