### ISSUE TITLE
Hide list when clicken selected style option

### ISSUE THREAD

**Issue by AgentSmith0** [el/style-switcher#18]
When you currently click the selected style option, the styles list won't get hidden, unlike the other options in the list. If you select one of them, the list disappears. To hide the list without selecting another style than the selected one, you need to click on the map outside of the list, which is not very user friendly in my opinion. Is it possible to change this behaviour?

**Comment by el** [comment]
Thanks for the feedback. I will implement this 👍

**Comment by el** [comment]
Done: https://github.com/el/style-switcher/commit/06135bef0453699463f0de43fe1f308937f4e400

**Comment by AgentSmith0** [comment]
Thank you very much!
