### ISSUE TITLE
If the defaultStyle is one of the available styles options, it should get the active status.

### ISSUE THREAD

**Issue by vcardins** [el/style-switcher#26]
Currently if the defaultStyle is one of the available styles options, it's entry doesn't get the `active` class and the option is not highlighted.
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2383329/219229932-839f24b2-74fa-4f38-9dd1-03fe7e7c5348.png">

**Comment by el** [comment]
Can you share your config?

**Comment by vcardins** [comment]
```
const config = {
	styles: [
		{ title: 'Satellite', uri: 'mapbox://styles/mapbox/satellite-v9' },
		{ title: 'Streets', uri: 'mapbox://styles/mapbox/streets-v9' },
		{ title: 'Satellite & Streets', uri: 'mapbox://styles/mapbox/satellite-streets-v11' },
		{ title: 'Satellite & Globe', uri: 'mapbox://styles/mapbox/satellite-streets-v12' },
	],
	options: {
		defaultStyle: 'mapbox://styles/mapbox/satellite-v9',
		preserveLayers: true,
	},
}
```

**Comment by el** [comment]
You need to pass the title of the default style. Please check the read me.
