### ISSUE TITLE
No code for onRemove method

### ISSUE THREAD

**Issue by thgautier92** [el/style-switcher#6]
To be able to translate each title, it's mandatory to remove the control and create a new on with translated titles.
There is no code in your OnRemove method.
According to the MapBox Api documentation [https://docs.mapbox.com/mapbox-gl-js/api/#icontrol](https://docs.mapbox.com/mapbox-gl-js/api/#icontrol)
please thanks add those 2 lines : 
  ```
    this.controlContainer.parentNode.removeChild(this.controlContainer);
      this._map = undefined;
```

**Comment by el** [comment]
Fixed with v1.0.6
