### ISSUE TITLE
support layer toggle method of switching styles

### ISSUE THREAD

**Issue by andrewharvey** [el/style-switcher#7]
One way I sometimes implement style switching is creating a single Style in Studio comprised of layers from multiple styles concatenated together, then to switch the style it's just a matter of toggling layers on and off.

I liked the UI and scaffolding your style-switcher provided so used it as a base and made that change at https://github.com/el/style-switcher/compare/master...alantgeo:toggle-layers

I took a few shortcuts when working on my fork, like removing all the TS so it's not PR ready), so this is more of a feature request, maybe it's worth supporting a few different styles of style switching, in particular this layer toggle method.

In my fork I also added a dist build using rollup which was handy for me.

**Comment by el** [comment]
Happy to consider it as an option if you create a proper PR :)

**Comment by andrewharvey** [comment]
I won't have the time for a PR, feel free to either leave this open as a feature request or close it.
